# Generated by Django 5.1.3 on 2024-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='username',
            field=models.CharField(blank=True, default='x', max_length=50, verbose_name='Чья новость'),
        ),
    ]
